# Generated by Django 5.2.17 on 2026-09-12 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('facilities', '0002_alter_facility_facility_number_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('department', models.CharField(choices=[('LABORATORY', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('CARDIOLOGY', 'Cardiology'), ('PATHOLOGY', 'Pathology')], max_length=30)),
                ('investigation_type', models.CharField(choices=[('LABORATORY', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('ECG', 'ECG'), ('ECHOCARDIOGRAPHY', 'Echocardiography'), ('PATHOLOGY', 'Pathology')], max_length=30)),
                ('investigation_name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=20)),
                ('clinical_indication', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=30)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='encounters.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='facilities.facility')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_investigations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='patients.patient')),
            ],
            options={
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['facility', 'investigation_number'], name='investigati_facilit_16e01f_idx'), models.Index(fields=['facility', 'patient'], name='investigati_facilit_8dd66b_idx'), models.Index(fields=['facility', 'encounter'], name='investigati_facilit_2a36ee_idx'), models.Index(fields=['facility', 'department', 'status'], name='investigati_facilit_fe7aad_idx'), models.Index(fields=['facility', 'ordered_at'], name='investigati_facilit_1a981c_idx')],
            },
        ),
    ]
