# Generated by Django 5.2.17 on 2026-09-12 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('facilities', '0002_alter_facility_facility_number_and_more'),
        ('investigations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['facility', 'department', 'status', 'priority'], name='investigati_facilit_465f0d_idx'),
        ),
    ]
