# Generated by Django 5.2.17 on 2026-09-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='facilities.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'facility', 'role'), name='unique_user_facility_role')],
            },
        ),
    ]
