# Generated by Django 5.2.17 on 2026-09-13 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0002_investigation_assigned_to_investigation_queued_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPECIMEN_COLLECTED', 'Specimen Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('specimen_collected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_specimens', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_order', to='investigations.investigation')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_laboratory_orders', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_laboratory_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('flag', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('ABNORMAL', 'Abnormal')], default='NORMAL', max_length=20)),
                ('interpretation', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_laboratory_results', to=settings.AUTH_USER_MODEL)),
                ('laboratory_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='laboratory.laboratoryorder')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HAEMATOLOGY', 'Haematology'), ('CHEMISTRY', 'Clinical Chemistry'), ('MICROBIOLOGY', 'Microbiology'), ('IMMUNOLOGY', 'Immunology'), ('SEROLOGY', 'Serology'), ('URINALYSIS', 'Urinalysis'), ('OTHER', 'Other')], max_length=30)),
                ('specimen_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='laboratory__categor_5e1eb4_idx')],
            },
        ),
        migrations.AddField(
            model_name='laboratoryorder',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_orders', to='laboratory.laboratorytest'),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(fields=['status', 'created_at'], name='laboratory__status_01649d_idx'),
        ),
    ]
