# Generated by Django 5.2.17 on 2026-09-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='laboratory.laboratoryorder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.laboratorytest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_laboratory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('flag', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('ABNORMAL', 'Abnormal')], default='NORMAL', max_length=20)),
                ('interpretation', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_laboratory_item_results', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='laboratory.laboratoryorderitem')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryPanelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_tests', to='laboratory.laboratorypanel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_test_memberships', to='laboratory.laboratorytest')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='laboratorypanel',
            name='tests',
            field=models.ManyToManyField(related_name='panels', through='laboratory.LaboratoryPanelTest', to='laboratory.laboratorytest'),
        ),
        migrations.CreateModel(
            name='LaboratorySpecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('specimen_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='COLLECTED', max_length=30)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_laboratory_specimens', to=settings.AUTH_USER_MODEL)),
                ('laboratory_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='laboratory.laboratoryorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_laboratory_specimens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='laboratoryorderitem',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.laboratoryspecimen'),
        ),
        migrations.AddConstraint(
            model_name='laboratorypaneltest',
            constraint=models.UniqueConstraint(fields=('panel', 'test'), name='unique_test_per_panel'),
        ),
        migrations.AddIndex(
            model_name='laboratoryspecimen',
            index=models.Index(fields=['laboratory_order', 'status'], name='laboratory__laborat_194e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryspecimen',
            index=models.Index(fields=['accession_number'], name='laboratory__accessi_5e389e_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryorderitem',
            index=models.Index(fields=['laboratory_order', 'status'], name='laboratory__laborat_bf76ac_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryorderitem',
            index=models.Index(fields=['test', 'status'], name='laboratory__test_id_53e1fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='laboratoryorderitem',
            constraint=models.UniqueConstraint(fields=('laboratory_order', 'test'), name='unique_test_per_laboratory_order'),
        ),
    ]
